language: node_js
node_js:
  - 12

branches:
  only:
  - main

services:
  - postgresql

before_script:
  - psql -c 'create database fruitbasket;' -U postgres
  - psql -a -d fruitbasket -f multiFruitBasket.SQL -U postgres